-- scripts/entries-schema.sql
--
-- Run once, by hand, in the Supabase SQL editor — this repo has no
-- migration runner (inbox and events, the app's other two tables, were
-- created the same way; scripts/funnel.sql is queries against them, not
-- their schema). Backs the contest feature: api/entries.js writes rows,
-- api/wall.js reads approved+wall_ok ones publicly, api/admin/entries.js
-- (behind ADMIN_SECRET) reads/moderates everything.
--
-- Unlike inbox/events, this table is NOT covered by api/cron/cleanup.js's
-- 30-day retention job — see rules.html's own retention clause. Nothing
-- deletes these rows automatically; deletion is manual, on request (see
-- privacy.html — contact info@almostsent.app).

create table if not exists entries (
  id bigint generated by default as identity primary key,
  sent text not null,        -- the text they were shown (PII-masked, same as inbox.sent)
  text text not null,        -- their own line, verbatim
  email text,                -- optional, only if they gave one
  device_id text,            -- same anonymous id the events table uses, not tied to identity
  wall_ok boolean not null default false,  -- opted into /wall at submission time
  approved boolean not null default false, -- set by a human at /admin/entries — never true on insert
  winner boolean not null default false,   -- set by a human at /admin/entries
  created_at timestamptz not null default now()
);

-- Speeds up /api/wall's own query (approved+wall_ok, newest first) —
-- optional, the table will work fine without it at contest scale, but
-- there's no reason not to have it.
create index if not exists entries_wall_idx on entries (approved, wall_ok, created_at desc);
